INSERT INTO fertilizante (nome, tipo) VALUES 
("Acido Borico" , "FERTILIZANTE"),
("Borax" , "FERTILIZANTE"),
("Calcario" , "FERTILIZANTE"),
("Cloreto De Potassio" , "FERTILIZANTE"),
("Fosfato Diamonico Dap" , "FERTILIZANTE"),
("Fosfato Monoamonico Map" , "FERTILIZANTE"),
("Fosfato Natural" , "FERTILIZANTE"),
("Nitrato De Amonio" , "FERTILIZANTE"),
("Nitrato De Calcio" , "FERTILIZANTE"),
("Oxido Cuproso" , "FERTILIZANTE"),
("Sulfato De Amonio" , "FERTILIZANTE"),
("Sulfato De Calcio" , "FERTILIZANTE"),
("Sulfato De Cobre" , "FERTILIZANTE"),
("Sulfato De Zinco" , "FERTILIZANTE"),
("Sulfato Manganoso" , "FERTILIZANTE"),
("Super Fosfato Simples" , "FERTILIZANTE"),
("Superfosfato Duplo" , "FERTILIZANTE"),
("Superfosfato Triplo" , "FERTILIZANTE"),
("Termofosfato" , "FERTILIZANTE"),
("Ureia" , "FERTILIZANTE"),
("Ureia Formaldeido" , "FERTILIZANTE"),
("Npk 10 10 10" , "FERTILIZANTE"),
("Npk 20 00 20" , "FERTILIZANTE"),
("Npk 20 05 20" , "FERTILIZANTE"),
("Npk 30 00 10" , "FERTILIZANTE"),
("Npk 30 00 20" , "FERTILIZANTE"),
("Aliette Wp" , "FUNGICIDA"),
("Alto 100 Concentrado Soluvel Sl" , "FUNGICIDA"),
("Amistar Wg Estrobirulina" , "FUNGICIDA"),
("Aproach Power Concentrado Emulsionavel" , "FUNGICIDA"),
("Aproach Prima Sc" , "FUNGICIDA"),
("Bio Imune Sc" , "FUNGICIDA"),
("Cantus Wg Viveiro" , "FUNGICIDA"),
("Comet Ec Estrobirulina" , "FUNGICIDA"),
("Cuprogard 350 Po Molhavel Wp" , "FUNGICIDA"),
("Cuprozeb Wp Ditiocarbamato" , "FUNGICIDA"),
("Elite 200 Ec" , "FUNGICIDA"),
("Fegatex Sl" , "FUNGICIDA"),
("Flexin Sc" , "FUNGICIDA"),
("Folicur 200 Ec" , "FUNGICIDA"),
("Garant Br Wp Viveiro" , "FUNGICIDA"),
("Impact 125 Sc" , "FUNGICIDA"),
("Kasumin" , "FUNGICIDA"),
("Nativo Sc Trifloxistrobina" , "FUNGICIDA"),
("Opera Suspoemulsao Se" , "FUNGICIDA"),
("Orkestra Sc" , "FUNGICIDA"),
("Premier Plus Sc" , "FUNGICIDA"),
("Priori Top Sc" , "FUNGICIDA"),
("Priori Xtra Sc" , "FUNGICIDA"),
("Recop Wp" , "FUNGICIDA"),
("Rovral Sc" , "FUNGICIDA"),
("Rovral Wp" , "FUNGICIDA"),
("Serenade" , "FUNGICIDA"),
("Simboll 125 Sc" , "FUNGICIDA"),
("Sphere Max Sc" , "FUNGICIDA"),
("Tenaz 250 Sc" , "FUNGICIDA"),
("Verdadero 600 Wg" , "FUNGICIDA"),
("Verismo Sc" , "INSETICIDA"),
("Sperto Wg" , "INSETICIDA"),
("Voliam Targo Sc" , "INSETICIDA"),
("Benevia Dispersao Oleo Od" , "INSETICIDA"),
("Durivo Sc" , "INSETICIDA"),
("Envidor Sc" , "INSETICIDA"),
("Oberon 240 Sc" , "INSETICIDA"),
("Abamectin Nortox Ec" , "INSETICIDA"),
("Vertimec 18 Ec" , "INSETICIDA"),
("Turbo Ec" , "INSETICIDA"),
("Talento 500 Wp" , "INSETICIDA"),
("Altacor 350 Wg" , "INSETICIDA"),
("Polytrin Ec" , "INSETICIDA"),
("Assist" , "INSETICIDA"),
("Nimbus Iharol Assist" , "INSETICIDA"),
("Agral Nonil Fenoxi Poli Etanol" , "INSETICIDA"),
("Goal Br Ec Concentrado Emulsionavel" , "HERBICIDA"),
("Flumyzin 500 Wp" , "HERBICIDA"),
("Diuron Nortox 800 Wp Po Molhavel" , "HERBICIDA"),
("Alion 500 Sc" , "HERBICIDA"),
("Sulfentrazone 500 Sc P" , "HERBICIDA"),
("Select 240 Ec" , "HERBICIDA"),
("Heat 700 Wg" , "HERBICIDA"),
("Accurate 600 Wg" , "HERBICIDA"),
("Clorimuron Master 250 Wg" , "HERBICIDA"),
("Aurora 400 Ec" , "HERBICIDA"),
("Glifosato Nortox 480 Concentrado Soluvel Sl" , "HERBICIDA"),
("Vegetal" , "ADJUVANTE"),
("Mineral" , "ADJUVANTE");